version: '3'
services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: app
    ports:
      - "4004:4004"
    env_file:
      - .env 
    depends_on:
      - mongo
    shm_size: '1gb'   #increase shared memory for puppeteer
    security_opt:
      - seccomp:unconfined  # allow puppeteer to run
    environment:
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

volumes:
  mongo_data:
